// <auto-generated />
using System;
using CutitBz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CutitBz.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191026175902_viewsInit")]
    partial class viewsInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("CutitBz.Models.Link", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("fullLink")
                        .HasColumnType("TEXT");

                    b.Property<int>("hits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("pin")
                        .HasColumnType("TEXT");

                    b.Property<string>("shortLink")
                        .HasColumnType("TEXT");

                    b.Property<int>("views")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("CutitBz.Models.View", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ip")
                        .HasColumnType("TEXT");

                    b.Property<string>("link")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Views");
                });
#pragma warning restore 612, 618
        }
    }
}
